# -*- coding: utf-8 -*-
"""Task07.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1eSqyK7AyqCXjSOrKArwjHZ6unlBCVHTk

**Task 07: Querying RDF(s)**
"""

!pip install rdflib
github_storage = "https://raw.githubusercontent.com/FacultadInformatica-LinkedData/Curso2023-2024/master/Assignment4/course_materials"

"""First let's read the RDF file"""

from rdflib import Graph, Namespace, Literal
from rdflib.namespace import RDF, RDFS
g = Graph()
g.namespace_manager.bind('ns', Namespace("http://somewhere#"), override=False)
g.namespace_manager.bind('vcard', Namespace("http://www.w3.org/2001/vcard-rdf/3.0#"), override=False)
g.parse(github_storage+"/rdf/example6.rdf", format="xml")

"""**TASK 7.1: List all subclasses of "LivingThing" with RDFLib and SPARQL**"""

from rdflib.plugins.sparql import prepareQuery

# RDFLib
ns = Namespace("http://somewhere#")
print(" - RDFLib: ")
for s,p,o in g.triples((None, RDFS.subClassOf, ns.LivingThing)):
  print(s)

# SPARQL
q1 = prepareQuery('''
  SELECT ?Class WHERE {
    ?Class rdfs:subClassOf ns:LivingThing
  }
  ''',
  initNs = { "ns": ns }
)

print("\n - SPARQL: ")
for r in g.query(q1):
  print(r.Class)

"""**TASK 7.2: List all individuals of "Person" with RDFLib and SPARQL (remember the subClasses)**

"""

# RDFLib
print(" - RDFLib: ")
# Person
for s,p,o in g.triples((None, RDF.type, ns.Person)):
  print(s)
# SubClassOf Person
for s,p,o in g.triples((None, RDFS.subClassOf, ns.Person)):
  for s,p,o in g.triples((None, RDF.type, s)):
    print(s)

# SPARQL
q2 = prepareQuery('''
  SELECT DISTINCT ?Person WHERE {
    {
      ?Person rdf:type ns:Person
    }
    UNION
    {
      ?subclass rdfs:subClassOf ns:Person.
      ?Person rdf:type ?subclass
    }
  }
  ''',
  initNs = { "ns": ns }
)

print("\n - SPARQL: ")
for r in g.query(q2):
  print(r.Person)

"""**TASK 7.3: List all individuals of "Person" or "Animal" and all their properties including their class with RDFLib and SPARQL. You do not need to list the individuals of the subclasses of person**

"""

# RDFLib
print(" - RDFLib: ")
# Person
for s,p,o in g.triples((None, RDF.type, ns.Person)):
  print("\nPerson:")
  print(s)
  print("Properties:")
  for s,p,o in g.triples((s, None, None)):
    print(p,o)
# Animal
for s,p,o in g.triples((None, RDF.type, ns.Animal)):
  print("\nAnimal:")
  print(s)
  print("Properties:")
  for s,p,o in g.triples((s, None, None)):
    print(p,o)

# SPARQL
q3 = prepareQuery('''
  SELECT ?Person ?Animal ?Property WHERE {
    {
      ?Person rdf:type ns:Person.
      ?Person ?Property ?Value
    }
    UNION
    {
      ?Animal rdf:type ns:Animal.
      ?Animal ?Property ?Value
    }
  }
  ''',
  initNs = { "ns": ns }
)

print("\n - SPARQL: ")
for r in g.query(q3):
  print(r.Person, r.Animal, r.Property)

"""**TASK 7.4:  List the name of the persons who know Rocky**"""

from rdflib import FOAF

vcard = Namespace("http://www.w3.org/2001/vcard-rdf/3.0/")

q4 = prepareQuery('''
  SELECT ?PersonName WHERE {
    ?Person rdf:type ns:Person.
    ?Person foaf:knows ns:RockySmith.
    ?Person vcard:Given ?PersonName
  }
  ''',
  initNs = { "ns": ns, "foaf": FOAF, "vcard": vcard }
)

# Visualize the results
for r in g.query(q4):
  print(r.PersonName)

"""**Task 7.5: List the entities who know at least two other entities in the graph**"""

from rdflib import FOAF

q5 = prepareQuery('''
  SELECT DISTINCT ?Entity WHERE {
    ?Entity foaf:knows ?Entity2;
            foaf:knows ?Entity3.
    FILTER (?Entity2 != ?Entity3)
  }
  ''',
  initNs = { "foaf": FOAF }
)

# Visualize the results
for r in g.query(q5):
  print(r.Entity)