PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX ns: <http://smartcity.linkeddata.es/lcc/ontology/energyConsumption#>

# Get Madrid Neighbourhoods and their links
SELECT * WHERE {
  ?sub a ns:Neighbourhood .
  ?sub owl:sameAs ?x
} LIMIT 10;

# Get  Madrid Districts and their links
SELECT * WHERE {
  ?sub a ns:District .
  ?sub owl:sameAs ?x 
} LIMIT 10;

# Get subjects that have buildingType predicate and are Centros culturales y bibliotecas.
SELECT *
WHERE {
  ?sub ns:buildingType "Centros culturales y bibliotecas".
} LIMIT 10;

# Get measure of Sensors higher than 5000 

SELECT *
WHERE {
  ?sub ns:consumption ?obj .
  FILTER (xsd:float(?obj) > 5000.0)
} LIMIT 1000









