SELECT ?counter
WHERE {
  ?counter <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://smart.city.linkeddata.es/lcc/ontology/G5O#Counter> .
}

SELECT ?station ?name ?capacity
WHERE {
   ?station <http://smart.city.linkeddata.es/lcc/ontology/G5O#hasName> ?name .
   ?station <http://smart.city.linkeddata.es/lcc/ontology/G5O#hasCapacity> ?capacity .
}

SELECT ?street ?wikidataEntity
WHERE {
   ?street <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://smart.city.linkeddata.es/lcc/ontology/G5O#Street> .
   ?street <http://www.w3.org/2002/07/owl#sameAs> ?wikidataEntity .
}