# -*- coding: utf-8 -*-
"""Task07.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ZmXiY6LoHUltKCumKG2nw7H1vJnd8BaW

**Task 07: Querying RDF(s)**
"""

!pip install rdflib
github_storage = "https://raw.githubusercontent.com/FacultadInformatica-LinkedData/Curso2023-2024/master/Assignment4/course_materials"

"""First let's read the RDF file"""

from rdflib import Graph, Namespace, Literal
from rdflib.namespace import RDF, RDFS
g = Graph()
g.namespace_manager.bind('ns', Namespace("http://somewhere#"), override=False)
g.namespace_manager.bind('vcard', Namespace("http://www.w3.org/2001/vcard-rdf/3.0#"), override=False)
g.parse(github_storage+"/rdf/example6.rdf", format="xml")

""":**TASK 7.1: List all subclasses of "LivingThing" with RDFLib and SPARQL**"""

# TO DO
from rdflib.plugins.sparql import prepareQuery

q1 = prepareQuery("""
    SELECT ?subClass
    WHERE {
        ?subClass rdfs:subClassOf ns:LivingThing .
    }
""", initNs={"ns": Namespace("http://somewhere#"), "rdfs": RDFS})

# Visualize the results
for r in g.query(q1):
  print(r)

"""**TASK 7.2: List all individuals of "Person" with RDFLib and SPARQL (remember the subClasses)**

"""

# TO DO
query = prepareQuery("""
    SELECT ?person
    WHERE {
        ?person a/rdfs:subClassOf* ns:Person .
    }
""", initNs={"ns": Namespace("http://somewhere#"), "rdfs": RDFS})

# Visualize the results
for r in g.query(query):
  print(r)

"""**TASK 7.3: List all individuals of "Person" or "Animal" and all their properties including their class with RDFLib and SPARQL. You do not need to list the individuals of the subclasses of person**

"""

# TO DO
query = prepareQuery("""
    SELECT ?individual ?property ?value ?class_
    WHERE {
        ?individual a ?class_ .
        ?individual ?property ?value .
        FILTER (?class_ = ns:Person || ?class_ = ns:Animal)
    }
""", initNs={"ns": Namespace("http://somewhere#")})

# Visualize the results
for row in g.query(query):
    print(f"Individual: {row.individual}")
    print(f"Class: {row.class_}")
    print(f"Property: {row.property}")
    print(f"Value: {row.value}")
    print()

"""**TASK 7.4:  List the name of the persons who know Rocky**

> Bloque con sangría


"""

# TO DO
query = prepareQuery("""
    SELECT ?name
    WHERE {
        ?person foaf:knows ?rocky .
        ?person ns:Given ?name .
        ?rocky ns:Given "Rocky" .
    }
""", initNs={"ns": Namespace("http://somewhere#")
   , "foaf": Namespace("http://xmlns.com/foaf/0.1/")})


# Visualize the results
for row in g.query(query):
    print(row.name)

"""**Task 7.5: List the entities who know at least two other entities in the graph**

> Bloque con sangría\


"""

# TO DO
# Visualize the results