# -*- coding: utf-8 -*-
"""Task05.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1RsL5W0YTYStLbtp-5-Zk0A7_PUrjeQs_

**Task 05: Reading and writing ontologies**
"""

!pip install rdflib
github_storage = "https://raw.githubusercontent.com/FacultadInformatica-LinkedData/Curso2021-2022/master/Assignment4/course_materials"

"""Leemos el fichero RDF de la forma que lo hemos venido haciendo"""

from rdflib import Graph, Namespace, Literal
g = Graph()
g.parse(github_storage+"/rdf/example4.rdf", format="xml")

"""Podemos comprobar las ternas que componen el documento de la misma forma.

"""

for s, p, o in g:
  print(s,p,o)

"""También podemos emplear otras herramientas como OntoSPY para visualizar una ontología"""

!pip install ontospy

from ontospy import Ontospy
data = '''

<?xml version="1.0"?>


<!DOCTYPE rdf:RDF [
    <!ENTITY xsd "http://www.w3.org/2001/XMLSchema#" >
    <!ENTITY rdfs "http://www.w3.org/2000/01/rdf-schema#" >
    <!ENTITY rdf "http://www.w3.org/1999/02/22-rdf-syntax-ns#" >
    <!ENTITY example4 "http://www.sowhere.com#" >
    <!ENTITY foaf "http://www.semanticweb.org/ontologies/example4.rdf#http://xmlns.com/foaf/0.1/" >
    <!ENTITY vcard-rdf "http://www.semanticweb.org/ontologies/example4.rdf#http://www.w3.org/2001/vcard-rdf/3.0/" >
]>


<rdf:RDF xmlns="http://www.sowhere.com#"
     xml:base="http://www.sowhere.com"
     xmlns:rdfs="http://www.w3.org/2000/01/rdf-schema#"
     xmlns:foaf="&example4;http://xmlns.com/foaf/0.1/"
     xmlns:xsd="http://www.w3.org/2001/XMLSchema#"
     xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#"
     xmlns:vcard-rdf="&example4;http://www.w3.org/2001/vcard-rdf/3.0/"
     xmlns:example4="http://www.semanticweb.org/ontologies/example4.rdf#">



    <!--
    ///////////////////////////////////////////////////////////////////////////////////////
    //
    // Object Properties
    //
    ///////////////////////////////////////////////////////////////////////////////////////
     -->




    <!-- http://www.semanticweb.org/ontologies/example4.rdf#http://xmlns.com/foaf/0.1/knows -->

    <rdf:Property rdf:about="#http://xmlns.com/foaf/0.1/knows"/>



    <!--
    ///////////////////////////////////////////////////////////////////////////////////////
    //
    // Data properties
    //
    ///////////////////////////////////////////////////////////////////////////////////////
     -->




    <!-- http://www.semanticweb.org/ontologies/example4.rdf#http://www.w3.org/2001/vcard-rdf/3.0/FN -->

    <rdfs:Datatype rdf:about="http://www.w3.org/2001/vcard-rdf/3.0/FN">
        <rdfs:range rdf:resource="&xsd;string"/>
    </rdfs:Datatype>



    <!-- http://www.semanticweb.org/ontologies/example4.rdf#http://www.w3.org/2001/vcard-rdf/3.0/Family -->

    <rdf:Property rdf:about="http://www.w3.org/2001/vcard-rdf/3.0/Family">
        <rdfs:domain rdf:resource="#Person"/>
        <rdfs:range rdf:resource="&xsd;string"/>
    </rdf:Property>



    <!-- http://www.semanticweb.org/ontologies/example4.rdf#http://www.w3.org/2001/vcard-rdf/3.0/Given -->

    <rdfs:Datatype rdf:about="#http://www.w3.org/2001/vcard-rdf/3.0/Given">
        <rdfs:domain rdf:resource="#Person"/>
        <rdfs:range rdf:resource="&xsd;string"/>
    </rdfs:Datatype>



    <!-- http://www.semanticweb.org/ontologies/example4.rdf#http://xmlns.com/foaf/0.1/email -->

    <rdfs:Datatype rdf:about="#http://xmlns.com/foaf/0.1/email">
        <rdfs:domain rdf:resource="#Person"/>
        <rdfs:range rdf:resource="&xsd;string"/>
    </rdfs:Datatype>



    <!--
    ///////////////////////////////////////////////////////////////////////////////////////
    //
    // Classes
    //
    ///////////////////////////////////////////////////////////////////////////////////////
     -->




    <!-- http://www.semanticweb.org/ontologies/example4.rdf#Person -->

    <rdfs:Class rdf:about="#Person"/>



    <!-- http://www.semanticweb.org/ontologies/example4.rdf#Researcher -->

    <rdfs:Class rdf:about="#Researcher">
        <rdfs:subClassOf rdf:resource="#Person"/>
    </rdfs:Class>



    <!--
    ///////////////////////////////////////////////////////////////////////////////////////
    //
    // Individuals
    //
    ///////////////////////////////////////////////////////////////////////////////////////
     -->




    <!-- http://www.semanticweb.org/ontologies/example4.rdf#JaneSmith -->

    <Person rdf:about="#JaneSmith">
        <vcard-rdf:Given rdf:datatype="&xsd;string">Jane</vcard-rdf:Given>
        <vcard-rdf:FN rdf:datatype="&xsd;string">Jane Smith</vcard-rdf:FN>
        <vcard-rdf:Family rdf:datatype="&xsd;string">Smith</vcard-rdf:Family>
        <foaf:email rdf:datatype="&xsd;string"
            >jSmith@somewhere.com</foaf:email>
    </Person>



    <!-- http://www.semanticweb.org/ontologies/example4.rdf#JohnSmith -->

    <Person rdf:about="#JohnSmith">
        <vcard-rdf:Given rdf:datatype="&xsd;string">John</vcard-rdf:Given>
        <vcard-rdf:FN rdf:datatype="&xsd;string">John Smith</vcard-rdf:FN>
        <vcard-rdf:Family rdf:datatype="&xsd;string">Smith</vcard-rdf:Family>
    </Person>
</rdf:RDF>



<!-- Generated by the OWL API (version 2.2.1.1138) http://owlapi.sourceforge.net -->



'''

model = Ontospy(data, verbose=True)
print(model.all_classes)
print(model.all_properties)

